microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/idpaykafkaconnect
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.idpay.internal.dev.cstar.pagopa.it"

  livenessProbe:
    create: true
    handlerType: 'exec'
    exec:
      command:
        - "/bin/sh"
        - "-c"
        - for connector in $(curl -s -X GET https://dev01.idpay.internal.dev.cstar.pagopa.it/idpaykafkaconnect/connectors | grep -Eo '[^]",\[]+'); do curl -s -X GET https://dev01.idpay.internal.dev.cstar.pagopa.it/idpaykafkaconnect/connectors/$connector/status | grep FAILED | wc -l; done | grep -Ez '^(0[[:space:]])+$']
    initialDelaySeconds: 20
    periodSeconds: 30
    failureThreshold: 15
    timeoutSeconds: 5

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "800Mi"
      cpu: "500m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envConfig:
    JAVA_TOOL_OPTIONS: "-javaagent:applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json"
    HEAP_OPTS: "-Xms256m -Xmx512m"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-d-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
